name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set git config
      run: |
        git config --global core.bigfilethreshold 100m
      shell:
        bash
    - name: Install Forc
      run: |
        curl -sSLf https://github.com/FuelLabs/sway/releases/download/v${{ inputs.forc-version }}/forc-binaries-linux_amd64.tar.gz -L -o forc.tar.gz
        tar -xvf forc.tar.gz
        chmod +x forc-binaries/forc
        mv forc-binaries/forc /usr/local/bin/forc
      shell:
        bash
    - uses: actions/checkout@v3
    - name: Build swaymigo
      run: |
        cd test
        ./build.sh
    - name: Run swaymigo tests
      run: |
        cd test
        cargo test --verbose
